In [46]:
## importing libraries
from bs4 import BeautifulSoup
import requests
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import requests
import time, os
import pandas as pd
from collections import OrderedDict
import pickle

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

import statsmodels.api as sm
import statsmodels.formula.api as smf

#standard scaler syntax
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [44]:
#open data frame
coreframe = pd.read_csv('finalfileselfcleaned.csv')

neededcolumns = ['PROPERTY TYPE', 'ADDRESS', 'CITY', 'ZIP OR POSTAL CODE', \
'PRICE', 'SQUARE FEET', 'LOT SIZE', 'YEAR BUILT', 'shortesttime', 'BEDS', 'BATHS']
coreframe = coreframe[neededcolumns]
coreframe = coreframe[np.isfinite(coreframe['BEDS']) & np.isfinite(coreframe['BATHS'])]
# can use np.isfinite() or pd.notna()
# https://stackoverflow.com/questions/13413590/how-to-drop-rows-of-pandas-dataframe-whose-value-in-a-certain-column-is-nan

,PROPERTY TYPE,ADDRESS,CITY,ZIP OR POSTAL CODE,PRICE,SQUARE FEET,LOT SIZE,YEAR BUILT,shortesttime,BEDS,BATHS
0,Condo/Co-op,1150 Folsom St #4,San Francisco,94103,1149000,1200,NaN,2000,12,1.0,1.5
1,Condo/Co-op,1542 Howard St,San Francisco,94103,965000,1207,NaN,1912,12,2.0,1.0
2,Condo/Co-op,1247 Harrison St #28,San Francisco,94103,969000,1083,NaN,2004,12,1.0,1.5
3,Condo/Co-op,380 10th St #26,San Francisco,94103,1199000,1372,NaN,2004,12,2.0,2.0
5,Condo/Co-op,776 Tehama St #9,San Francisco,94103,430500,418,NaN,2006,12,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
1596,Townhouse,21103 Gary Dr Unit 111A,Hayward,94546,529950,1100,NaN,1993,38,2.0,2.0
1597,Single Family Residential,22526 Charlene Way,Castro Valley,94546,1075000,2327,14450.0,1954,38,4.0,2.5
1599,Single Family Residential,2764 Tribune Ave,Hayward,9454,1499900,3358,4890.0,1990,38,8.0,7.0
1600,Single Family Residential,1228 Thornwall Ln,Hayward,9454,674950,1285,5187.0,1956,38,3.0,2.0
1601,Single Family Residential,29600 Palomares Rd,Castro Valley,94552,1123000,1425,29620.0,2003,36,1.0,3.0

In [68]:
#general syntax to get x and y variables

x_cols = ['SQUARE FEET', 'YEAR BUILT', 'shortesttime', 'BEDS', 'BATHS']
X = coreframe[x_cols]
y = coreframe['PRICE']

#simple split of training data
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
       
## This step fits the Standard Scaler to the training data
## Essentially it finds the mean and standard deviation of each variable in the training set

std = StandardScaler()
std.fit(X_train.values)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [69]:
model = sm.OLS(y_train, X_train)
fit = model.fit()
fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  PRICE   R-squared (uncentered):                   0.731
Model:                            OLS   Adj. R-squared (uncentered):              0.730
Method:                 Least Squares   F-statistic:                              657.6
Date:                Fri, 24 Jan 2020   Prob (F-statistic):                        0.00
Time:                        01:12:27   Log-Likelihood:                         -18624.
No. Observations:                1212   AIC:                                  3.726e+04
Df Residuals:                    1207   BIC:                                  3.728e+04
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
SQUARE FEET   1112.5146     46.946     23.698      0.000    1020.409    1204.620
YEAR BUILT     121.1530     54.950      2.205      0.028      13.345     228.961
shortesttime -1.557e+04   2713.093     -5.739      0.000   -2.09e+04   -1.02e+04
BEDS         -1.607e+05   3.49e+04     -4.608      0.000   -2.29e+05   -9.23e+04
BATHS         -251.9073   5.65e+04     -0.004      0.996   -1.11e+05    1.11e+05
==============================================================================
Omnibus:                     1462.393   Durbin-Watson:                   1.957
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           548679.710
Skew:                           5.660   Prob(JB):                         0.00
Kurtosis:                     106.619   Cond. No.                     5.19e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.19e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""